name: Installation Testing

on: push

jobs:
  ubuntu:
    strategy:
      matrix:
        runner: [ubuntu-22.04, ubuntu-20.04, macos-12]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Run installer
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/EIE2-IAC-Labs/Lab0-devtools/${{ github.sha }}/tools/install.sh)

      - name: Run toolchain test
        run: |
          cd ~/Documents/iac/lab0-devtools/autumn/workspace/toolchain && make tb_toolchain

      - name: Run toolchain Verilator test
        run: |
          cd ~/Documents/iac/lab0-devtools/autumn/workspace/toolchain && make tb_verilator
